---
dist: bionic
matrix:
  fast_finish: true
  include:
    - os: linux
      env:
        - ANSIBLE='ansible>=2.8'
        - MOLECULE_SCENARIO="default"
      services: docker
      language: python
      python: "3.8"
#    - os: linux
#      env:
#        - ANSIBLE='ansible>=2.8'
#        - MOLECULE_SCENARIO="default"
#        - MOLECULE_DISTRIBUTION="archlinux"
#        - MOLECULE_IMAGE="manjarolinux/base:latest"
#      services: docker
#      language: python
#      python: "3.8"

install:
  - pip3 install -U pip
  - pip3 install "$ANSIBLE" testinfra molecule docker flake8 ansible-lint yamllint
script:
  - python --version
  - molecule --version
  - ansible --version
  - openssl aes-256-cbc -K $encrypted_48d092bfe7cc_key -iv $encrypted_48d092bfe7cc_iv -in .ci/vaultkey.enc -out $HOME/vaultkey -d
  - ANSIBLE_VAULT_PASSWORD_FILE=$HOME/vaultkey molecule test -s $MOLECULE_SCENARIO

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
