---
- name: Add yubikey system group
  group:
    name: yubikey
    state: present
    system: yes
  when:
    - yubikey_add_system_group

- name: Configure yubikey users
  include_tasks: configure-yubikey-users.yml
  with_items: "{{ yubikey_users }}"
  loop_control:
    loop_var: yubikey_user
  when: yubikey_users|default([])|length

- name: Configure pam for OpenSSH Server
  include_tasks: configure-sshd.yml
  when:
    - yubikey_config_sshd|default(false)
    - yubikey_api_id is defined
    - yubikey_api_key is defined

- name: Configure pam for sudo user
  include_tasks: configure-sudo.yml
  when:
    - yubikey_config_sudo|default(false)
    - yubikey_api_id is defined
    - yubikey_api_key is defined

- name: Configure polkit-1
  include_tasks: configure-polkit.yml
  when:
    - yubikey_config_polkit|default(false)
    - yubikey_api_id is defined
    - yubikey_api_key is defined

- name: Configure pam for login
  include_tasks: configure-login.yml
  when:
    - yubikey_config_login|default(false)
    - yubikey_api_id is defined
    - yubikey_api_key is defined

- name: Allow ypbind on SELinux, yubico module depends on it.
  seboolean:
    name: allow_ypbind
    state: yes
    persistent: true
  when:
    - ansible_selinux['status']|default('disabled') == "enabled"

- name: Allow yubico login on SELinux
  seboolean:
    name: authlogin_yubikey
    state: yes
    persistent: true
  when:
    - ansible_selinux['status']|default('disabled') == "enabled"
