---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: lxd
lint: |
  set -e
  PATH=${PATH}
  yamllint .
  ansible-lint -x 208 .
  ansible-lint molecule/resources/playbooks/converge.yml
  flake8
platforms:
  - name: "yubikey-${MLDISTRO:-ubuntu}"
    alias: "${MLIMG:-ubuntu/focal}"
provisioner:
  name: ansible
  playbooks:
    create: ../resources/playbooks/create.yml
    converge: ../resources/playbooks/converge.yml
    destroy: ../resources/playbooks/destroy.yml
verifier:
  name: testinfra
  directory: ../resources/tests/
  options:
    verbose: true
